site_name: WFRMLS Python API Wrapper
site_description: Official Python wrapper for the Wasatch Front Regional MLS (WFRMLS) API
site_author: WFRMLS API Team
site_url: https://theperrygroup.github.io/wfrmls/

# Repository
repo_name: wfrmls
repo_url: https://github.com/theperrygroup/wfrmls
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 WFRMLS API Team

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/home-city
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_if_no_docstring: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: theperrygroup
      repo: wfrmls
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Authentication: getting-started/authentication.md
    - First Steps: getting-started/first-steps.md
  - Guides:
    - Overview: guides/index.md
    - Property Search: guides/property-search.md
    - Member Management: guides/member-management.md
    - Data Synchronization: guides/data-synchronization.md
    - Error Handling: guides/error-handling.md
    - Best Practices: guides/best-practices.md
    - Performance Optimization: guides/performance-optimization.md
    - Troubleshooting: guides/troubleshooting.md
  - API Reference:
    - Overview: api/index.md
    - Core Client: api/client.md
    - Properties: api/properties.md
    - Members: api/members.md
    - Offices: api/offices.md
    - Open Houses: api/openhouse.md
    - Data System: api/data-system.md
    - Lookups: api/lookup.md
    - Specialized APIs: api/specialized.md
  - Examples:
    - Overview: examples/index.md
    - Basic Usage: examples/basic-usage.md
    - Advanced Patterns: examples/advanced-patterns.md
    - Integration Examples: examples/integration-examples.md
    - Real-World Scenarios: examples/real-world-scenarios.md
  - Reference:
    - Overview: reference/index.md
    - Error Codes: reference/error-codes.md
    - Rate Limits: reference/rate-limits.md
    - Field Reference: reference/field-reference.md
    - OData Queries: reference/odata-queries.md
    - Changelog: reference/changelog.md
  - Development:
    - Overview: development/index.md
    - Contributing: development/contributing.md
    - Development Setup: development/development-setup.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
    - Code Style Guide: development/style-guide.md
    - Documentation Style Guide: documentation-style-guide.md
  - Legal:
    - Overview: legal/index.md
    - License: legal/license.md
    - Terms of Service: legal/terms-of-service.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theperrygroup/wfrmls
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wfrmls/
    - icon: material/home
      link: https://utahrealestate.com
    - icon: material/book-open
      link: https://theperrygroup.github.io/wfrmls/
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with actual Google Analytics ID
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Watch extra directories
watch:
  - wfrmls/
  - docs/ 